/*
 
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
 
Examples:
 
Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:

Input: s = "", t = "y"
Output: "y"

Example 3:

Input: s = "a", t = "aa"
Output: "a"

Example 4:

Input: s = "ae", t = "aea"
Output: "a"
 
Link: https://leetcode.com/problems/find-the-difference/
 
*/

import Foundation

class Solution {
    
    func findTheDifference(_ s: String, _ t: String) -> Character {
        
        let dictS = putInADictionary(s)
        let dictT = putInADictionary(t)
        
        if dictS.count != dictT.count {
            
            let tKeys = Set(dictT.keys)
            let sKeys = Set(dictS.keys)
            
            return tKeys.symmetricDifference(sKeys).first ?? emptyChar()
            
        } else {
            
            for (k, v) in dictS {
                if dictT[k] ?? 0 > v {
                    return k
                }
            }
        }
        
        return emptyChar()
    }
    
    private func putInADictionary(_ s: String) -> [Character: Int] {
        
        var dict: [Character: Int] = [:]
        
        for character in s {
            
            if let times = dict[character] {
                dict[character] = times + 1
            } else {
                dict[character] = 1
            }
        }
        
        return dict
    }
    
    private func emptyChar() -> Character {
        return "".first! // empty char in swift?
    }
}
